### ISSUE TITLE
[Suggestion] Reload Shotgun while bat is out.

### ISSUE THREAD

**Issue by Thresh90** [klipsey/ScoutMod#1]
I know the mod literally came out in a day and some polishing has yet to really be done, but gonna point this out even if its obvious lol

I strongly believe that the skill cooldowns should lower when switching skills/loadouts, so that way folks aren't stuck swapping back and still waiting for weapons to be reloaded/replenished

It seems like it somewhat does this but not exactly fast enough, also a audio cue of when its done reloading the first loadout would be nice

**Comment by klipsey** [comment]
already fixed. reload still needs to be actively done but has been buffed to increase with attackspeed and a lower base reload speed
