### ISSUE TITLE
Multiple bones are rotated improperly.

### ISSUE THREAD

**Issue by TrulySc** [klipsey/ScoutMod#4]
First off, before anything else, gotta say I love this mod, atm scout is my favorite character to play as if I just want to hop in for a quick runthrough ror2. So thanks for the amazing implementation of the bostonian in ror.

The model for scout right now is kind of jank, as I assume you are aware. I know things like item placements are using a temporary fix, as noted in another issue #2 , but the actual root cause of the problem this person was having in this issue seems to be a rigging problem that is not exclusive to the head region. 

As a fun experiment, I decided to try to make a skin for scout, with no prior expirence with ror2 modding, but my export had a few problems, mainly a rotated waist, legs, and head. Thinking I made a mistake, I decided to check with the modelswapper skins mod [https://thunderstore.io/package/Goorakh/ModelSwapperSkins/](url) which dynamically reweights the rigs of characters and enemies, and almost all characters had the same issue.
![Screenshot_20240509_132858](https://github.com/klipsey/ScoutMod/assets/59325034/4bc55200-c6d7-42fc-84a8-cd2038969067)
![Screenshot_20240509_132832](https://github.com/klipsey/ScoutMod/assets/59325034/907d961c-0ebb-4e5b-96b8-0b6fd336e277)
![Screenshot_20240509_132821](https://github.com/klipsey/ScoutMod/assets/59325034/5777af96-6523-4c44-9122-c35a65a418f7)

Again, I'm sure you are aware of this, but just in case, thought i'd give a heads up. Thanks for the mod and the fun runs it has given me so far!

**Comment by klipsey** [comment]
weird, ill fix it rq if i can. it uses a modified driver rig so there might have been some jank there

**Comment by klipsey** [comment]
update, fixing the bones breaks all the animations so it's gonna take a while to get working. For any skins you make, the jank should fix itself after I fix it so don't worry about having to wait

**Comment by klipsey** [comment]
Fixed
